"""update book model

Revision ID: 3908611d2d7e
Revises: 9e2059d2a45b
Create Date: 2021-05-02 12:47:26.231689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3908611d2d7e'
down_revision = '9e2059d2a45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('book', 'descrption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('descrption', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('book', 'description')
    # ### end Alembic commands ###
